name: cellranger_mkref
namespace: cellranger
description: Build a Cell Ranger-compatible reference folder from user-supplied genome FASTA and gene GTF files.
keywords: [ cellranger, single-cell, rna-seq, alignment, reference, gtf, fasta ]
links:
  documentation: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/advanced/references#header
  repository: https://github.com/10XGenomics/cellranger/blob/main/lib/python/cellranger/reference_builder.py
  homepage: https://www.10xgenomics.com/support/software/cell-ranger/latest
  issue_tracker: https://github.com/10XGenomics/cellranger/issues
references:
  doi: 10.1038/ncomms14049
license: Copyright (c) 2023 10x Genomics
authors:
  - __merge__: /src/_authors/emma_rousseau.yaml
    roles: [ author ]
arguments:
  # inputs
  - type: file
    name: --genome_fasta
    required: true
    description: Reference genome fasta.
    example: genome_sequence.fa.gz
  - type: file
    name: --transcriptome_gtf
    required: true
    description: Reference transcriptome annotation.
    example: transcriptome_annotation.gtf.gz
  - type: string
    name: "--reference_version"
    description: "Optional reference version string to include with reference"
  - type: file
    name: --output
    direction: output
    required: true
    description: Output folder
    example: cellranger_reference
resources:
  - type: bash_script
    path: script.sh
test_resources:
  - type: bash_script
    path: test.sh
  - path: test_data

engines:
- type: docker
  image: quay.io/nf-core/cellranger:8.0.0
  setup:
    - type: docker
      run: |
        DEBIAN_FRONTEND=noninteractive apt update && \
        apt upgrade -y && apt install -y procps pigz && rm -rf /var/lib/apt/lists/*
  test_setup:
    - type: apt
      packages: [ git, wget ]
    - type: docker
      run: |
        TARGETARCH="${TARGETARCH:-$(dpkg --print-architecture)}" && \
        TARGETOS="${TARGETOS:-linux}" && \
        PATH="${PATH}:/usr/local/go/bin" && \
        wget https://go.dev/dl/go1.21.4.$TARGETOS-$TARGETARCH.tar.gz && tar -C /usr/local/ -xzf go1.21.4.$TARGETOS-$TARGETARCH.tar.gz && \
        rm go1.21.4.$TARGETOS-$TARGETARCH.tar.gz && \
        git clone --branch v2.5.0 https://github.com/shenwei356/seqkit.git && \
        cd seqkit/seqkit/ && go build && cp seqkit /usr/bin/ && cd ../../ && rm -rf seqkit && rm -r /usr/local/go
    - type: docker
      run: |
        cellranger --version | sed 's/ cellranger-/: /' > /var/software_versions.txt

runners:
- type: executable
- type: nextflow
  directives:
    label: [ highmem, highcpu ]
